name: fintxn
version: '1.0.0'
profile: fintxn

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  fintxn:
    staging:
      +schema: staging
      +materialized: view
    marts:
      +schema: marts
      +materialized: table
